Bug 538988 - New widget: Character input field with length restriction
EclipseNebula/nebula pull request #102
Opened 2019-08-01 15:08 UTC by uenal-akkaya

Change-Id: I0b48ceb34b5e62af3679198f45d5844af08a4da1
Signed-off-by: Uenal Akkaya <uenal.akkaya@sap.com>

2019-08-01 15:19 UTC, wimjongman commented
jenkins, ok to test

2019-09-05 20:18 UTC, lcaron requested changes

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +public class TextFieldWithEvaluation extends Composite {
General comment about this file : please add Javadoc to add public methods

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/Evaluation.java
> +package org.eclipse.nebula.widgets.TextFieldWithEvaluation;
General comment : please add header comments for all files

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/MaxLengthEvaluator.java
> +	private static final String E4_DARK_THEME_ID = "org.eclipse.e4.ui.css.theme.e4_dark";
Question to @wimjongman : this class relies on Eclipse E4 ThemeEngine.
What is the philosophy of nebula : should we need to depends on e4 engine, or should we be compatible with V3.X version ?

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/MaxLengthEvaluator.java
> +		return isDarkTheme() ? gray : dark_gray;
Can we think about customisable colors instead of private methods ?

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		input.addMouseListener(new MouseAdapter() {
please use lambda like input.addListener(SWT.MouseUp, e-> validate());
You can also factorize the code because you call numerous times the validate() method

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		hint.pack();
To avoid flickering effect maybe we should use 
try {
    setRedraw(false);
    ...
} finally {
   setRedraw(true); redraw(); update();
}

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		this.evaluator = evaluator;
Add checkWidget()

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		this.evaluator = evaluator;
Once the evaluator is set up, the widget should be re-created (dispose all children then call create() then updateLayout();

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +				validate();
is it necessary to call validate() twice on mouse up and mouse down ?

2019-09-05 20:18 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +				validate();
is it necessary to call validate() twice on key up and key down ?

2019-09-06 13:33 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/MaxLengthEvaluator.java
> +	private static final String E4_DARK_THEME_ID = "org.eclipse.e4.ui.css.theme.e4_dark";
The theming specific code should be placed in a separate plugin and feature. Please see this widget as example:

https://github.com/eclipse/nebula/tree/master/widgets/pshelf

2019-11-14 21:01 UTC, lcaron reviewed
Some changes has to be performed in headers because Nebula moved to EPL v2
It's a nice widget and the code is very easy to read, congrats.

2019-11-14 21:01 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/META-INF/MANIFEST.MF
> +Require-Bundle: org.eclipse.core.runtime;bundle-version="3.15.0",
Please remove bundle version for the 3 required bundles

2019-11-14 21:01 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/Evaluation.java
> +package org.eclipse.nebula.widgets.TextFieldWithEvaluation;
Since the previous commit, nebula has moved to EPL V2. Please update the headers

2019-11-14 21:01 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/example/Example.java
> +/*******************************************************************************
In nebula, most snippets and examples are located in a dedicated plug-in

2019-12-04 09:34 UTC, uenal-akkaya commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/example/Example.java
> +/*******************************************************************************
hi Icaron,

Thanks for your help and guidence.
I implemented the changes and added also a tests plugin with unit tests.

Regards,
Ünal

2019-12-05 18:23 UTC, lcaron requested changes
Very good job, and good idea to include the example.
The only things left are changes to EPL V2.0

Once it is done, it could be included in Nebula 2.3.0 for the Christmas 2019 Release !!

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/META-INF/MANIFEST.MF
> + org.eclipse.e4.ui.css.swt.theme;bundle-version="0.12.200"
do you still use this plug in ?

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/build.properties
> +# All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/plugin.properties
> +# All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/pom.xml
> +All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/build.properties
> +# All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/plugin.properties
> +# All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:23 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/pom.xml
> +All rights reserved. This program and the accompanying materials
Please update to EPL 2.0

2019-12-05 18:24 UTC, lcaron commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/example/Example.java
> +/*******************************************************************************
You're welcome. It's almost done :)

2019-12-06 12:41 UTC, uenal-akkaya commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/META-INF/MANIFEST.MF
> + org.eclipse.e4.ui.css.swt.theme;bundle-version="0.12.200"
no. I made the colors configurable via setters and getters.

2019-12-07 15:21 UTC, lcaron approved these changes

2019-12-07 15:21 UTC, lcaron commented
Very good job, congrats

2019-12-08 18:47 UTC, wimjongman requested changes

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/META-INF/MANIFEST.MF
> + org.eclipse.jface;
This Require-Bundle header is not correct.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/build.properties
> +# Copyright (C) 2019 Uenal Akkaya <uenal.akkaya@sap.com>, Michael Gutfleisch <michael.gutfleisch@sap.com>
We also need explicit consent from Michale Gutfleisch. Michael needs to comment on the pull request and also must sign the Eclipse Contributor agreement. We probably also need consent from the SAP company.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/plugin.properties
> +providerName=
Provider name needs to be filled in with Eclipse Nebula

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/.project
> +	<name>org.eclipse.nebula.widgets.textfieldwithevaluation.example</name>
The project name does not match org.eclipse.nebula.widgets.valitext.example

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: org.eclipse.nebula.widgets.textfieldwithevaluation.example
Bundle name does not match git folder name

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/META-INF/MANIFEST.MF
> +Export-Package: org.eclipse.nebula.widgets.TextFieldWithEvaluation.example;version="1.0.0"
package name not correct

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/plugin.properties
> +pluginName=Nebula TextFieldWithEvaluation Example Plug-in
Is this the widget name?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/pom.xml
> +Copyright (C) 2019, SAP SE
Copyright is different from other copyright

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.example/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/example/Example.java
> +* Copyright (C) 2019 Uenal Akkaya <uenal.akkaya@sap.com>, Michael Gutfleisch <michael.gutfleisch@sap.com>
Copyright is different here

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
Bundle and package names must match git folder name

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/plugin.properties
> +providerName=
Provider name: Eclipse Nebula

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext.tests/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/tests/Example.java
> +public class Example {
Code duplication. Use the class from examples plugin?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/.project
> +	<name>org.eclipse.nebula.widgets.textfieldwithevaluation</name>
Project name and package name should match git folder name

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: org.eclipse.nebula.widgets.textfieldwithevaluation
Bundle name and package names

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/plugin.properties
> +providerName=
providername: Eclipse Nebula

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/Evaluation.java
> +package org.eclipse.nebula.widgets.TextFieldWithEvaluation;
Package name should match git folder name

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/Evaluation.java
> + * Evaluation object containing information about evaluation text and text font color.
Javadoc not clear. What is this class supposed to do?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/Evaluation.java
> +	 * @param text The evaluation text
Why do we have a constructor with font and color?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/IEvaluator.java
> +	Evaluation evaluate(String text);
What is the difference between evaluate and isvalid?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/MaxLengthEvaluator.java
> +		Color evaluationTextColor = length > maxLength ? getInvalidColor() : getValidColor();
isValid should be called here. Now code is duplicated.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/MaxLengthEvaluator.java
> +	 * @param validColor
wrong param name.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +	public TextFieldWithEvaluation(Composite parent, int maxLength) {
Default widget constructor always must have parent and then the style bit (int). Composite, int with a different meaning is confusing.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +	 * Constructor which can uses the given {@link IEvaluator} to evaluate the text.
spelling

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +	public TextFieldWithEvaluation(Composite parent, IEvaluator evaluator) {
Suggest to also pass the style bit. SWT.NONE default makes this constructor less usable.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +	 * Constructor which can uses the given {@link IEvaluator} to evaluate the text.
spelling

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +	public TextFieldWithEvaluation(Composite parent, int style, IEvaluator evaluator) {
remove previous constructor that passes SWT.NONE

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		this.input.selectAll();
style nit: use this.input or input this.input is more clear because there is no name like fInput that tells maintainers it is a field.

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +		hint = new Label(this, SWT.READ_ONLY);
this.hint or fHint?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +
why the empty lines?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +
Why the empty lines?

2019-12-08 18:47 UTC, wimjongman commented on widgets/valitext/org.eclipse.nebula.widgets.valitext/src/org/eclipse/nebula/widgets/TextFieldWithEvaluation/TextFieldWithEvaluation.java
> +
why the empty lines?

2019-12-08 18:49 UTC, wimjongman commented
We also need a feature project. See other widgets for example.

2019-12-08 19:23 UTC, wimjongman commented
I ran the example and I have a couple of comments/questions.

1. Why is there not an option to block further input on the text? Why does it let people type any further if we know the field is in error?

2. I am confused about what the difference is between evaluate and isValid. Why are there two methods. Maybe add isValid to IEvaluation class

3. I think you are passing the style bits to the composite. This is not correct. The style bits must be passed to the Text widget. TextWithEvaluation must add evaluation to Text but not take anything away from it.

For example, the following is not working when added to the example class.

     	new TextFieldWithEvaluation(shell, SWT.PASSWORD, new MaxLengthEvaluator(5));
	TextFieldWithEvaluation textFieldWithEvaluation = new TextFieldWithEvaluation(shell, SWT.MULTI,
				new MaxLengthEvaluator(5));
		GridDataFactory.fillDefaults().grab(true, true).applyTo(textFieldWithEvaluation);

These are very basic Text styles that don't work in your widget. 

4. Clicking out of the field sometimes hides the label. In other cases, the label is not hidden. Why does it behave like that? It does not seem intentional. 

5. Your tests project does not contain JUnit tests. Please add unit tests or remove the bundle.

2020-02-20 13:17 UTC, lcaron commented
Hi Unal,

Any news about this new widget ? If you need help feel free to ask !

Thank you

Laurent

2020-03-05 16:58 UTC, wimjongman commented
Closing. Reopen when you plan to pick this up again.

2020-03-05 16:58 UTC, closed without merging