feature[TW15669]: Rework Viewer Multi-Edit in nebula
EclipseNebula/nebula pull request #198
Opened 2019-12-19 00:05 UTC by jmidvidy

2019-12-19 07:00 UTC, lcaron submitted a review, later dismissed

2019-12-19 07:16 UTC, lcaron requested changes
A few comments to use lambda and manage i18n, but it is a great job. Congrats

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/action/ColumnMultiEditAction.java
> +      ListDialogSortableFiltered ld = new ListDialogSortableFiltered(title, "Select an attribute.", new PatternFilter(),
Should use XViewerText.get(XX) for internationalisation. Please do not forget both German an French Translation
(for French it is "Sélectionner un attribut")

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +      // provided for subclass implementation
Like the comment (very useful) 👍

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +   public void setInitialSelections(Collection<? extends Object> initialSelections) {
Why use plural ?
setInitialSelection seems more relevant

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +      treeViewer.getViewer().addSelectionChangedListener(new ISelectionChangedListener() {
Please use lambda

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +      treeViewer.getViewer().addDoubleClickListener(new IDoubleClickListener() {
Please use lambda

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +      treeViewer.getFilterControl().addModifyListener(new ModifyListener() {
Please use lambda

2019-12-19 07:16 UTC, lcaron commented on widgets/xviewer/org.eclipse.nebula.widgets.xviewer/src/org/eclipse/nebula/widgets/xviewer/util/internal/dialog/ListDialogSortableFiltered.java
> +         statusLabel.setText("Error!");
Please use getText for i18n

2020-01-29 03:49 UTC, dondunne commented
Aborting this as Jeremy isn't committing to Nebula anymore.  I merged this change into another commit and resolved comments, except the Lambda ones.

2020-01-29 03:49 UTC, closed without merging