Issue #304 Grid.onPaint is ineffient on large grids
EclipseNebula/nebula pull request #305
Opened 2021-03-16 08:38 UTC by laeubi

I have don some small adjustments that for my case increases the speed dramatically at least after the final load. I'd like to provide these here as a draft to get some feedback and/or discussions.

- store index on cell to prevent linear list lookups
- don't paint headers that are out of view
- break if width is larger than view

2021-03-16 14:52 UTC, tomsontom requested changes

2021-03-16 14:52 UTC, tomsontom commented on widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
> +			column.index = index;
you need to sync all indices after that one

2021-03-16 14:52 UTC, tomsontom commented on widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
>  	int newColumn(final GridColumn column, final int index) {
beside handling the `newColumn` you also have to handle the `removeColumn` and fix all indices

2021-03-16 15:18 UTC, laeubi commented
FYI @wimjongman as I can't add reviewer to a PR...

2021-03-16 15:34 UTC, tomsontom requested changes

2021-03-16 15:34 UTC, tomsontom commented on widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
> +							emptyCellRenderer.setColumn(indexOf(column));
you could use the cached value where to save the method call and the checks

2021-03-16 15:34 UTC, tomsontom commented on widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
> +							emptyCellRenderer.setBounds(x, y, width, getItemHeight());
you could move the getItemHeight() out of the loop or access it directly to by pass the check

2021-03-16 15:34 UTC, tomsontom commented on widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
> +				emptyCellRenderer.setBounds(x, y, clientArea.width - x, getItemHeight());
you can directly access the getItemHeight() or save it and reuse it below

2021-03-22 10:52 UTC, wimjongman commented
Moving to that Tycho version caused an issue. I think the dependency has to be added explicitly to the manifest of grid.css

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.2.0:compile (default-compile) on project org.eclipse.nebula.widgets.grid.css: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/agent/workspace/nebula.stable.github/widgets/grid/org.eclipse.nebula.widgets.grid.css/src/org/eclipse/nebula/widgets/grid/css/GridElementProvider.java: 
[ERROR] 	/*******************************************************************************
[ERROR] 	^
[ERROR] The type org.w3c.dom.css.CSSValue cannot be resolved. It is indirectly referenced from required .class files
```

2021-04-02 15:35 UTC, wimjongman commented
@laeubi, Please take a look at the failing build.

2021-05-11 11:00 UTC, tomsontom approved these changes

2021-05-11 11:40 UTC, laeubi commented
Could this be merged or is anything left?

2021-05-11 12:06 UTC, tomsontom commented
as I'm not directly involved anymore I let @wimjongman merge it - i only looked through the code and can't comment on build, versioning stuff, ...

2021-05-11 14:39 UTC, merged