Move FormattedText from incubation to release #515
EclipseNebula/nebula pull request #519
Opened 2023-05-24 13:55 UTC by chrhem

Needed to add FormattedText widget to incubation reactor build because DateChooser has a dependency to it

2023-05-24 15:26 UTC, wimjongman requested changes
Thanks for the patch @chrhem. 

I think there are some category.xml that sites also have to be changed. Can you take a look at that?

2023-05-24 15:26 UTC, wimjongman commented on releng/org.eclipse.nebula.nebula-incubation/pom.xml
> +		<module>../../widgets/formattedtext</module>
Please move the line back to the original location.

2023-05-25 08:08 UTC, chrhem commented
Hi @wimjongman , thanks for the quick review.
category.xml's are updated. PDE tooling changed some whitespaces. If this is unwanted i could revert that.
The line in the incubation pom.xml is back in it's old location.

2023-05-25 13:15 UTC, wimjongman approved these changes

2023-05-25 13:16 UTC, merged

2023-05-25 13:16 UTC, wimjongman commented
Thank you!! @chrhem