Bug 548149 - Allow min/max date to show the allowed range
EclipseNebula/nebula pull request #99
Opened 2019-06-20 12:24 UTC by sibeon

in the Calendar and to limit wrong selection

This new feature allowes to set min and max date to avoid selecting invalide date.
handled min max in:
- text entry - only valid dates can be entered in the text field. If date is invalid and no previous date is selected the Datepicker will be opend.
- date picker - invalid dates are set to enabled=false, today button makes date visible if today is not valid.

Signed-off-by: Stefan Nöbauer <stefan.noebauer@kgu-consulting.com>

2019-06-20 13:00 UTC, wimjongman commented on widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java
> +		if (date != null) {
Code smell ;) You alter the input parameter.

2019-06-20 13:02 UTC, wimjongman commented on widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java
> +	public Calendar getMinDate() {
Allows mindate to be altered. Is this your intention? If so then state that in the javadoc. If not then return a clone of mindate.

2019-06-20 13:03 UTC, wimjongman commented on widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTime.java
> +	public Calendar getMaxDate() {
Allows maxdate to be altered. Is this your intention? If so then state that in the javadoc. If not then return a clone of maxdate.

2019-06-20 13:03 UTC, wimjongman commented on widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTimeBuilder.java
> +	public Calendar getMinDate() {
Allows date to be altered. Is this your intention? If so then state that in the javadoc. If not then return a clone of date.

2019-06-20 13:04 UTC, wimjongman commented on widgets/cdatetime/org.eclipse.nebula.widgets.cdatetime/src/org/eclipse/nebula/widgets/cdatetime/CDateTimeBuilder.java
> +	 * @return Returns the maxDate.
Allows date to be altered. Is this your intention? If so then state that in the javadoc. If not then return a clone of date.

2019-06-20 13:05 UTC, wimjongman requested changes
Hi Stefan, Thanks for the patch. Please take a look at my comments.

2019-06-20 13:13 UTC, wimjongman commented
jenkins, add to whitelist

2019-06-20 14:17 UTC, sibeon commented
OK I pushed some changes.

2019-07-02 07:24 UTC, sibeon commented
Hi
Can I do anything here to move forward?

2019-07-02 11:12 UTC, wimjongman commented
Stefan, there is a build error. If you take a look at the log you can find what is wrong.

I think the CDateTime parent pom needs updating as well. You can find it one directory higher from the project.

2019-07-09 12:37 UTC, wimjongman commented
retest this please

2019-07-15 10:38 UTC, sibeon commented
> 
> 
> retest this please

Rebased on upstream/master and retested.

2019-07-15 13:39 UTC, merged

2019-07-15 13:39 UTC, wimjongman commented
Thanks Stefan!